export const COFFEES_LOADING = 'COFFEES_LOADING';
export const ADD_COFFEES = 'ADD_COFFEES';
export const COFFEES_FAILED = 'COFFEES_FAILED';

export const SUITES_LOADING = 'SUITES_LOADING';
export const ADD_SUITES = 'ADD_SUITES';
export const SUITES_FAILED = 'SUITES_FAILED';

export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';

export const CLOTHES_LOADING = 'CLOTHES_LOADING';
export const ADD_CLOTHES = 'ADD_CLOTHES';
export const CLOTHES_FAILED = 'CLOTHES_FAILED';

export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_FAILED = 'CART_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
